apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-review-ingress
  namespace: book-review-dev
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # Backend API
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: book-review-backend
            port:
              number: 3001

      # Frontend (NO rewrite)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: book-review-frontend
            port:
              number: 80
